### ISSUE TITLE
cannot import APIClient

### ISSUE THREAD

**Issue by gozhang7** [michaelliao/sinaweibopy#21]
When I trying to use the weibo package, I get a error to import the APIClient. Python raises a error that "cannot import name APIClient" , does someone know why?

The source code is showing below:
from weibo import APIClient(error here)
import webbrowser

**Comment by kachuti** [comment]
Hello 
I too get the same error .
can you help me ?
please .
Python 2.7.5 (default, Aug 18 2016, 15:58:25) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>  from weibo import APIClient
  File "<stdin>", line 1
    from weibo import APIClient
    ^
IndentationError: unexpected indent
