### ISSUE TITLE
不支持 OAuth2/revokeoauth2 接口？

### ISSUE THREAD

**Issue by JokerQyou** [michaelliao/sinaweibopy#52]
如题。
官方文档写得也很模糊，不知道是大写还是全小写。使用 `client.oauth2.revokeoauth2.get()` 和 `client.OAuth2.revokeoauth2.get()` 都不行。
PS，这个接口不是在 `/2/` 路径下的。

**Comment by michaelliao** [comment]
不支持revokeoauth2接口
