### ISSUE TITLE
不能发表微博：weibo.APIError: APIError: 10014: Insufficient app permissions!, request: /2/statuses/update.json

### ISSUE THREAD

**Issue by jiangjiangflies** [michaelliao/sinaweibopy#59]
weibo.APIError: APIError: 10014: Insufficient app permissions!, request: /2/statuses/update.json

**Comment by michaelliao** [comment]
这是新浪限制了你的app权限，和sdk无关

**Comment by jiangjiangflies** [comment]
不是的，update接口已经关了。。

**Comment by frankYaohua** [comment]
那请问有什么解决方法吗？谢谢啦！

**Comment by jiangjiangflies** [comment]
用share，具体可以查看微博api

**Comment by frankYaohua** [comment]
感谢，我试试看

**Comment by frankYaohua** [comment]
share post request时一直不成功..老是显示HTTP METHOD is not suported for this request!
请问你有成功吗？谢谢啦！ @jiangjiangflies 请问有什么需要注意的吗？

**Comment by benbendemo** [comment]
测试发现，确实是微博API将"statuses/update"接口关掉导致返回10014报错。官网里已经没有这个接口，提供了一个"statuses/share"接口。[API地址](http://open.weibo.com/wiki/微博API)

使用旧的API，报错信息如下图。
![statuses/update API报错信息](https://user-images.githubusercontent.com/4705587/38799268-9833f734-4196-11e8-9714-2ae1caca2772.jpg)

使用新的接口测试成功，如下图。
![statuses/share API成功信息](https://user-images.githubusercontent.com/4705587/38799289-adc832cc-4196-11e8-8e78-94df84327f77.jpg)

然后显示来自一个“未通过审核应用”。😂
