### ISSUE TITLE
Any plan to support python 3

### ISSUE THREAD

**Issue by dsin** [michaelliao/sinaweibopy#71]
Error when try to build on python 3
```
File "sinaweibopy/weibo.py", line 12, in <module>
        from cStringIO import StringIO
    ModuleNotFoundError: No module named 'cStringIO'
```

**Comment by fengh16** [comment]
I have modified this code to support python3. You can get it from https://github.com/fengh16/sinaweibopy/blob/37b31103a04db7268ad14e0e802d826158f81a23/weibo.py

**Comment by dsin** [comment]
Awesome 👍 

Thank you very much
